# Generated by Django 5.0.3 on 2024-03-09 11:03

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewExperienceApp', '0002_interviewexperience_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewexperience',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interviewexperience',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='id'),
        ),
    ]
